# Generated by Django 5.0.7 on 2025-03-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_invoice_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paid',
        ),
    ]
