# Generated by Django 5.0.7 on 2025-02-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_tournament_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('Division', 'Division'), ('3rd/4th Playoff', '3rd/4th Playoff'), ('5th/6th Playoff', '5th/6th Playoff'), ('7th/8th Playoff', '7th/8th Playoff'), ('9th/10th Playoff', '9th/10th Playoff'), ('Quarter-Final', 'Quarter-Final'), ('Semi-Final', 'Semi-Final'), ('Final', 'Final'), ('Free', 'Free')], default='Division', max_length=20),
        ),
    ]
