# Generated by Django 5.0.7 on 2025-03-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_alter_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='umpireOneName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UmpireOne', to='tournaments.entry'),
        ),
        migrations.AddField(
            model_name='match',
            name='umpireTwoName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UmpireTwo', to='tournaments.entry'),
        ),
    ]
