# Generated by Django 5.0.7 on 2025-03-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_match_umpireonename_match_umpiretwoname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='umpireOne',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpireTwo',
        ),
    ]
