# Generated by Django 5.0.7 on 2025-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0035_alter_tournament_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
