# Generated by Django 5.0.7 on 2025-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0040_alter_tournament_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='notes',
            field=models.TextField(blank=True, default='Entry & attendance at the tournament is deemed to be consent for photographs to be taken and used by the organiser, Hockey Fever. Clubs are entirely responsible for ensuring that anyone attending has photographic consent. Please inform organisers if someone associated with your club does not have consent, each time they attend a tournament. \n\nPlayers & Coaches MUST wait off the pitch area when they are not playing in a tournament game. \n\nSpectators MUST remain behind the barriers (Teams may have one coach, one manager and one umpire on the sideline of the pitch area during games)'),
        ),
    ]
