# Generated by Django 5.0.7 on 2025-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0042_entry_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='endTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
