# Generated by Django 5.0.7 on 2025-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0043_tournament_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('County', 'County'), ('Regional', 'Regional'), ('National', 'National'), ('Festival', 'Festival'), ('N/A', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='noDivisions',
            field=models.IntegerField(default=1),
        ),
    ]
