# Generated by Django 5.0.7 on 2025-07-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0044_alter_tournament_level_alter_tournament_nodivisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='startTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
