# Generated by Django 5.0.7 on 2025-07-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0045_alter_tournament_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='noDivisions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
