# Generated by Django 5.0.7 on 2025-09-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0047_alter_tournament_nodivisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='splitDivs',
            field=models.BooleanField(default=False),
        ),
    ]
