# Generated by Django 5.0.7 on 2025-09-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0048_tournament_splitdivs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitDivTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divNumber', models.IntegerField(default=0)),
                ('noPitches', models.IntegerField(default=1)),
                ('startTime', models.TimeField(blank=True, default=None, null=True)),
                ('matchType', models.CharField(choices=[('One Way', 'One Way'), ('Each Way', 'Each Way')], default='One Way', max_length=10)),
                ('matchDuration', models.IntegerField(default=15)),
                ('halftimeDuration', models.IntegerField(default=0)),
                ('breakDuration', models.IntegerField(default=5)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
