# Generated by Django 5.0.7 on 2025-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
