# Generated by Django 5.0.7 on 2025-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_schedule_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='umpire_published',
            field=models.BooleanField(default=False),
        ),
    ]
